#pragma once

#define DEFAULT_RENDER_AREA_WIDTH 64
#define DEFAULT_RENDER_AREA_HEIGHT 24

#define MAX_VERTICES 4096

#define MAX_MODEL_MATRICIES 32
#define MAX_PROJECTION_MATRICIES 2
#define MAX_TEXTURE_MATRICIES 2
#define MAX_LIGHTS 8

#define MAX_DISPLAY_LISTS 64

#define PIXSOFTGL_VERSION "1.1"
#define PIXSOFTGL_EXTENSIONS ""
#define PIXSOFTGL_VENDOR "PixelBrushArt"
#define PIXSOFTGL_RENDERER "PixSoftGL"
