#pragma once

#define DEFAULT_RENDER_AREA_WIDTH 64
#define DEFAULT_RENDER_AREA_HEIGHT 24

#define MAX_VERTICES 4096

#define MAX_LIGHTS 8
#define MAX_CLIP_PLANES 6
#define MAX_MODELVIEW_STACK_DEPTH 32
#define MAX_PROJECTION_STACK_DEPTH 2
#define MAX_TEXTURE_STACK_DEPTH 2
#define SUBPIXEL_BITS 4
#define MAX_TEXTURE_SIZE 64
#define MAX_PIXEL_MAP_TABLE 32
#define MAX_NAME_STACK_DEPTH 64
#define MAX_LIST_NESTING 64
#define MAX_EVAL_ORDER 8
//#define MAX_VIEWPORT_DIMS
#define MAX_ATTRIB_STACK_DEPTH 16
#define MAX_CLIENT_ATTRIB_STACK_DEPTH 16

#define MAX_DISPLAY_LIST_COMMANDS 4096
#define MAX_DISPLAY_LIST_ENTRIES 1024
#define MAX_TEXTURES 256


#define RGBA_MODE false
#define INDEX_MODE false
#define DOUBLEBUFFER false
#define STEREO false
#define RED_BITS 8
#define GREEN_BITS 8
#define BLUE_BITS 8
#define ALPHA_BITS 0
#define INDEX_BITS 0
#define DEPTH_BITS 32

#define PIXSOFTGL_VERSION "1.1"
#define PIXSOFTGL_EXTENSIONS ""
#define PIXSOFTGL_VENDOR "PixelBrushArt"
#define PIXSOFTGL_RENDERER "PixSoftGL"
